### ISSUE TITLE
The number of JS event listeners is growing

### ISSUE THREAD

**Issue by kulakowka** [video-react/video-react#89] opened 2018-02-27 14:17 UTC
### Issue description

- version `latest`
- browser: `all`

### Steps to reproduce issue

You must add the `shouldComponentUpdate()` method to all components where event listeners are added to the render method. 
(For example: `<Video>`)

Otherwise, the number of JS event listeners increases. This is clearly visible on long videos. Try opening the Performance monitor in the latest version of Chrome. 

![2018-02-27 17 16 28](https://user-images.githubusercontent.com/557190/36733545-fdca7f26-1be1-11e8-9dbf-a2c93c294e1b.png)

**Comment by JimLiu** [comment] 2018-02-28 02:12
I don't think that's caused by the re-render, the re-render won't add new event listeners.

But we do have an issue with `addEventListener`, it fixed in
https://github.com/video-react/video-react/pull/85/files

**Closed** 2018-02-28 15:38 UTC
