### ISSUE TITLE
ReplayControl & ForwardControl Limited to [5, 10,30]

### ISSUE THREAD

**Issue by paolavness** [video-react/video-react#254] opened 2019-03-26 14:24 UTC
**Describe the bug**
When setting the ReplayControl & ForwardControl to custom value, below warning thrown and buttons disappear from control bar. Area where buttons are meant to appear is still clickable and work with given `seconds` value.

`Warning: Failed prop type: Invalid prop 'seconds' of value '1' supplied to 'ReplayControl', expected one of [5,10,30].`

**To Reproduce**
1. Add custom <ControlBar /> as per below.
```
<ControlBar autoHide={false}>
	<ReplayControl seconds={1} order={1.1} />
	<ForwardControl seconds={7} order={1.2} />
	...
</ControlBar>
```
3. See warning in consol
2. Click on area where Replay and Forward controls are meant to be
3. See media scan Forwards or Replay correctly as per `seconds`

**Expected behavior**
Said controls should work with any Number value given and should not throw an error.

**Desktop (please complete the following information):**
 - OS:  Mac High Safari
 - Browser: latest Chrome
 - Video-React Version:  0.10.4

**Comment by mondaychen** [comment] 2019-03-26 15:59
This is by design. We are using material design icons for the forward/replay buttons. Since they only offer 5, 10, 30 icons, they are what we can support for this feature. https://material.io/tools/icons/?search=forward&icon=forward_5&style=baseline

I think these three options are good enough for most use cases. 1 second is usually too small when you are forwarding/rewinding, and 7 seconds is pretty close to 5. If you really need to build a customized button, you can build your own component. See https://video-react.js.org/customize/customize-component/

If you can come up with a solution that can help build good icons for any numbers, we'd welcome a PR, and I'll change this issue into a new feature discussion thread. Otherwise, I'm closing this.

**Closed by mondaychen** 2019-03-26 15:59 UTC
Labels: bug report

**Comment by paolavness** [comment] 2019-03-26 16:19
I see your point re the design. My use case is possibly fringe and I have had several users ask for more refined control over these buttons. In the example I gave, `1` and `7` were just to prove the bug :) 

Despite this, it would be better if the video player did not break when non-conforming numbers were used. 

Another point is that if a user decides to use custom icons for the ControlBar, they will still experience this breaking limitation, unless custom icons require customized components? 

A better solution would be to throw the warning but use a default icon to prevent the video player from breaking. If this is possible, I would be grateful. In my specific case again, the controls are so small the number in the icon is not visible. 

Is this possible?

Thank you,
Paola

**Comment by mondaychen** [comment] 2019-03-26 21:00
The error you see is just a PropTypes check. You won't see it when you are in production mode.

I don't like the idea of having a warning message for a fringe use case. I will still recommend using a customized component for your case. You have access to `actions` in your customized component, so you can simply call `actions.forward` and `actions.replay` to do the trick.

**Comment by paolavness** [comment] 2019-03-27 08:39
Hello again,
I appreciate what you saying about not wanting to change things for a fringe case. I aslo appreciate the amount of work and improvements you have been making on the platform. We've been using `video-react` for over two years and its great to see activity. We're still a small team, otherwise I'd most definitely to a PR on this.

The problem tho is not the `warning`. As you say, in `production` mode the warning does not display . 

The problem is that in even in `production` mode, the video player `ReplayControl` and/or `ForwardControl` buttons disappear, as in the below image: 

![Screen Shot 2019-03-27 at 9 29 58 AM](https://user-images.githubusercontent.com/20376932/55061267-9606cd00-5073-11e9-9e28-59b40327a62b.png)

I've tried to find the right area in the `video-react` code which causes this but havn't yet. I imagine tho that using a default icon would solve this issue and be simple fix (famous last words!! :) while making the `video-react` more robust. 

Warmly,
Paola

**Comment by mondaychen** [comment] 2019-04-04 22:11
Hi @paolavness 

I think having a default icon will be pretty confusing to users. Imagine you have forward buttons with seconds 1, 3, 5, 7, you see a special icon for 5, while the rest are all the same.

For your use case, my suggestion is 1. you can try build a custom component, as I mentioned it should not be too hard 2. because the css controlling the icon is simply `video-react-icon-forward-${seconds}`, you can add custom css to define your own icon.

**Comment by paolavness** [comment] 2019-04-05 17:09
Yeah it could be confusing for users. My player buttons are quite small - the number is not visible.
And yes, I did created custom buttons for my usage. Thanks for the link on how to do this 👍
