### ISSUE TITLE
HLS Source doesn't work

### ISSUE THREAD

**Issue by Mueslint** [video-react/video-react#167] opened 2018-10-03 10:11 UTC
### Issue description

- version `#0.13.0`
- browser: `chrome 69.0.3497.100`

### Steps to reproduce issue
Follow the guide:
https://video-react.js.org/customize/customize-source/

### Steps to reproduce
1. I copy pasted this class as I suppose it works (no knowledge on that)
```javascript
import React, { Component } from 'react';
import Hls from 'hls.js';

export default class HLSSource extends Component {
  constructor(props, context) {
    super(props, context);
    this.hls = new Hls();
  }

  componentDidMount() {
    const { src, video } = this.props;
    if (Hls.isSupported()) {
      this.hls.loadSource(src);
      this.hls.attachMedia(video);
      this.hls.on(Hls.Events.MANIFEST_PARSED, () => {
        video.play();
      });
    }
  }

  render() {
    return (
      <source
        src={this.props.src}
        type={this.props.type || 'application/x-mpegURL'}
      />
    );
  }
}
```
2. Import and wrap it with the Player component
```javascript
<Player fluid={false} width={640} height={480}>
   <HLSSource
      isVideoChild
       src="http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8"
    />
</Player>
```
3. `npm start`

### Expected behaviour
It should read .m3u8 content

### Actual behaviour
It doesn't, loading screen loop 

### Demo
Here is the code sandbox as it is more explicit
https://codesandbox.io/s/l2k5ql01ol

**Comment by marek-sed** [comment] 2018-10-05 09:18
Tried today it is working for me just copied the example

**Comment by mondaychen** [comment] 2019-03-18 15:00
I can't reproduce it. Can you check everything and try again? If there's no further information provided, I'll have to close this issue.

**Closed** 2019-06-12 15:22 UTC
Labels: can't reproduce

**Comment by MadeByDouglas** [comment] 2019-08-09 21:57
any updates on this? we are having this issue and right now that code sandbox link is not working, just loading screen loop.

**Comment by mondaychen** [comment] 2019-08-09 21:59
@MadeByDouglas can you make a code sandbox demo about it? If I have enough information I can investigate more.

**Comment by MadeByDouglas** [comment] 2019-08-09 22:15
I don't, sorry, we are using react so I'm investigating this thread https://github.com/video-dev/hls.js/issues/2064

**Comment by MadeByDouglas** [comment] 2019-08-09 22:19
also the demo at https://video-react.js.org/customize/customize-source/ does not work in safari

**Comment by JimLiu** [comment] 2019-08-10 16:41
@MadeByDouglas 
you just need to change `new Hls();` to `new Hls({ enableWorker: false });`

I'll update the example

**Comment by vamsimudadla** [comment] 2019-12-03 06:34
It's not working for me. It is showing the screen loop

**Comment by kuabhish** [comment] 2020-08-02 15:05
this problem is still not solved. Any suggessstions ?

**Comment by wenotch** [comment] 2023-04-05 10:56
problem still exist
